services:
  accounts:
    image: satyam519/accounts:s4
    container_name: accounts-ms
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank

  cards:
    image: satyam519/cards:s4
    container_name: cards-ms
    ports:
      - 9000:9000
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
  loans:
    image: satyam519/loans:s4
    container_name: loans-ms
    ports:
      - 8090:8090
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank

networks:
  eazybank:
    driver: "bridge"
